# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root.
root = "."
tmp_dir = "tmp"

[build]
# Watch these filename extensions.
include_ext = ["go", "tmpl", "css", "js"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "node_modules"]
# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]
